# -*- coding: utf-8 -*-
"""DV TASK-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vN9ZkCIgUI3fl9tRTDQq5GGKz0zlGDJ2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AAPL.csv.xls")

df.head()

print("Shape of dataset:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

print("Missing Values:")
print(df.isnull().sum())

df['Date'] = pd.to_datetime(df['Date'])
columns = ['Open', 'High', 'Low', 'Close', 'Volume']

for col in columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df = df.dropna(subset=columns)
df = df.sort_values('Date')
print(df.head())

df = df[['Date', 'Open', 'High', 'Low', 'Close', 'Volume']]

df.head()

df['Price_Delta'] = df['Close'] - df['Open']

df[['Date', 'Open', 'Close', 'Price_Delta']].head(10)

df['Daily_Return'] = ((df['Close'] - df['Open']) / df['Open']) * 100

df[['Date', 'Open', 'Close', 'Daily_Return']].head(10)

plt.figure(figsize=(12,5))

plt.plot(df['Date'], df['Volume'])

plt.title('Trading Volume Trend')
plt.xlabel('Date')
plt.ylabel('Volume')

plt.xticks(rotation=45)
plt.show()

average_volume = df['Volume'].mean()

print("Average Trading Volume:", average_volume)

volume_mean = df['Volume'].mean()
volume_std = df['Volume'].std()

volume_limit = volume_mean + (2 * volume_std)

anomalous_days = df[df['Volume'] > volume_limit]

print("Anomalous Trading Days:")
print(anomalous_days[['Date', 'Volume']])

plt.figure(figsize=(12,5))

plt.plot(df['Date'], df['Volume'], label='Trading Volume')

plt.axhline(volume_limit, linestyle='--', label='Anomaly Limit')

plt.title('Trading Volume and Anomalous Days')
plt.xlabel('Date')
plt.ylabel('Volume')

plt.xticks(rotation=45)
plt.legend()
plt.show()

plt.figure(figsize=(8,5))

plt.hist(df['Daily_Return'], bins=30)

plt.title('Daily Return Distribution')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')

plt.show()

mean_return = df['Daily_Return'].mean()
variance_return = df['Daily_Return'].var()
std_return = df['Daily_Return'].std()

print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)

print("Stock Return Distribution Summary")
print("---------------------------------")
print("Mean Return:", round(mean_return, 4))
print("Variance:", round(variance_return, 4))
print("Standard Deviation:", round(std_return, 4))

df.head(10)

df.to_csv('AAPL_cleaned.csv', index=False)

print("Cleaned dataset saved successfully.")

